# Generated by Django 4.2.3 on 2023-07-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
