# Generated by Django 4.2.3 on 2023-07-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_api", "0002_user_is_staff_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_country", models.CharField(max_length=50)),
                ("origin_city", models.CharField(max_length=50)),
                ("destination_country", models.CharField(max_length=50)),
                ("destination_city", models.CharField(max_length=50)),
                ("departure_time", models.TimeField()),
                ("departure_date", models.DateField()),
                ("total_seats_left", models.IntegerField(default=60)),
                ("economy_fare", models.IntegerField()),
                ("business_fare", models.IntegerField()),
            ],
        ),
    ]
