# Generated by Django 4.2.3 on 2023-07-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_api", "0004_ticket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="business_fare",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="fare",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="economy_fare",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat_number",
            field=models.CharField(max_length=60),
        ),
    ]
